---

- hosts: all
  become: true
  tasks:

  - name: Install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install updates (Ubuntu)
    apt:
#      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  tasks:

  - name: Install apache and php packages for Ubuntu.
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: centos
  become: true
  tasks:

  - name: Install apache and php packages for CentOS.
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"