---

- hosts: all
  become: true
  tasks:

  - name: Remove apache2 package.
    apt:
      name: apache2
      state: absent

  - name: Remove php support for apache package.
    apt:
      name: libapache2-mod-php
      state: absent